FROM francken/php

RUN install-php-extensions xdebug pcov

ADD php-testing.ini /usr/local/etc/php/php.ini

# Install git so that we can use coveralls
RUN apt-get update \
    && apt-get install -y git \
    && rm -rf /var/lib/apt

CMD ["vendor/bin/phpunit", "--coverage-text"]
