version: '2'

services:
  php:
    build:
      dockerfile: Dockerfile
      context: ./Docker/php
    image: francken/php
    links:
      - mysql
    volumes:
      - ./Francken/:/var/www/francken

  queue-worker:
    build:
      dockerfile: Dockerfile-queue
      context: ./Docker/php
    image: francken/queue-worker
    volumes:
      - ./Francken/:/var/www/francken
    restart: always

  scheduler:
    build:
      dockerfile: Dockerfile-scheduler
      context: ./Docker/php
    image: francken/scheduler
    volumes:
      - ./Francken/:/var/www/francken
    restart: always

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./Docker/nginx
    image: francken/nginx
    ports:
      - 80:80
      - 443:443
    links:
      - php
    volumes_from:
      - php
    restart: always

  mysql:
    build:
      dockerfile: Dockerfile
      context: ./Docker/mysql
    image: francken/mysql
    environment:
      - MYSQL_USER=francken
      - MYSQL_PASSWORD=leden
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=francken
    restart: always

  composer:
    image: composer/composer:alpine
    volumes_from:
      - php
    working_dir: /var/www/francken

  npm:
    image: node:14.5
    volumes_from:
      - php
    working_dir: /var/www/francken

  yarn:
    image: kkarczmarczyk/node-yarn
    volumes_from:
      - php
    working_dir: /var/www/francken
    command: yarn

# This service is mostly identical to the php service except that it also
# intalls xdebug so we can check for coverage
  test_coverage:
    build:
      dockerfile: Dockerfile-testing
      context: ./Docker/php
    image: francken/php-with-xdebug
    volumes_from:
      - php
    links:
      - mysql
    environment:
      DB_CONNECTION: testing
