version: '2'

services:
  php:
    build:
      dockerfile: Dockerfile
      context: ./Docker/php7-fpm
      args:
        UID: 1000
    links:
      - mysql
    volumes:
      - ./Francken/:/var/www/francken
    working_dir: /var/www/francken

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./Docker/nginx
    ports:
      - 80:80
      - 443:443
    links:
      - php
    volumes:
      - ./Francken/:/var/www/francken
    restart: always

  mysql:
    image: mysql:8.0
    volumes:
      - ./Docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_USER=francken
      - MYSQL_PASSWORD=leden
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=francken
    restart: always

  composer:
    image: composer/composer:alpine
    volumes:
      - ./Francken:/var/www/francken
    working_dir: /var/www/francken

# This service is mostly identical to the php service except that it also
# intalls xdebug so we can check for coverage
  test_coverage:
    build:
      dockerfile: Dockerfile
      context: ./Docker/testing
    command: vendor/bin/phpunit
    volumes:
      - ./Francken:/var/www/francken
    links:
      - mysql
    environment:
      DB_CONNECTION: testing
    working_dir: /var/www/francken
